### ISSUE TITLE
fails to build on docs.rs

### ISSUE THREAD

**Issue by PonasKovas** [qdot/libappindicator-rs#10]

**Comment by qdot** [comment]
Yeah this is also filed on qdot/systray-rs#36 for similar reasons. Not quite sure how to fix it yet.

**Comment by jyn514** [comment]
Fixed by https://github.com/rust-lang/crates-build-env/pull/59. I queued a rebuild so you don't have to publish a new release :) https://docs.rs/crate/libappindicator-sys/0.5.0

**Comment by qdot** [comment]
Closing, though will probably need to open a new bug at some point because what's generated on docs.rs is now unreadable.

**Comment by qdot** [comment]
And thanks! :D
